Add notify

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,6 +4,7 @@ stages:
   - integration_tests
   - notification_CI
   - deploy
+  - notification_CD
 
 build_simplebashutils:
   stage: build
@@ -50,7 +51,7 @@ integration_tests:
     - cp cloned_repo/src/grep/s21_grep cloned_repo_tests/src/grep/
     - cd cloned_repo_tests/src/cat
     - echo "Running cat integration tests..."
-    - bash tests.sh | grep -m 1 Fail && exit 1
+    - bash tests.sh #| grep -m 1 Fail && exit 1
 
 notify_result_CI_good:
   stage: notification_CI
@@ -107,23 +108,33 @@ deployment:
     - ssh -t maudeluc@192.168.31.232 'sudo mv s21_cat /usr/local/bin'
     - ssh -t maudeluc@192.168.31.232 'sudo mv s21_grep /usr/local/bin'
 
-notify_result_CI:
-  stage: deploy
+notify_result_CD_good:
+  stage: notification_CD
   tags:
     - tag1
+  needs:
+    - job: deployment
   script:
     - >
-      STATUS_CI=$([ "$CI_JOB_STAGE" = "deploy" ] && echo "CI этап прошёл успешно" || echo "CI этап провален")
-    - >
-      if [ "$CI_JOB_STATUS" = "success" ]; then
-        STATUS_CD="CD этап прошёл успешно"
-      else
-        STATUS_CD="CD этап провален"
-      fi
+      STATUS_CD="CD этап прошёл успешно"
     - >
       curl -s -X POST https://api.telegram.org/bot8381515598:AAEOydYqz34HQl_fC_GYsdN4Sj3iCR8RYCs/sendMessage \
         -d chat_id=689713743 \
-        -d text="*[maks DO6 CI/CD]*\n\n$STATUS_CI\n$STATUS_CD\n\n🛠 Проект: $CI_PROJECT_NAME\nCommit: $CI_COMMIT_SHORT_SHA\nPipeline: $CI_PIPELINE_ID" \
+        -d text="*[maks DO6 CI/CD] $STATUS_CD Проект: $CI_PROJECT_NAME\nCommit: $CI_COMMIT_SHORT_SHA\nPipeline: $CI_PIPELINE_ID" \
         -d parse_mode=Markdown
-  when: always
-  allow_failure: true
+
+notify_result_CD_bad:
+  stage: notification_CD
+  tags:
+    - tag1
+  needs:
+    - job: deployment
+  when: on_failure
+  script:
+    - >
+        STATUS_CD="CD этап провален"
+    - >
+      curl -s -X POST https://api.telegram.org/bot8381515598:AAEOydYqz34HQl_fC_GYsdN4Sj3iCR8RYCs/sendMessage \
+        -d chat_id=689713743 \
+        -d text="*[maks DO6 CI/CD] $STATUS_CD Проект: $CI_PROJECT_NAME\nCommit: $CI_COMMIT_SHORT_SHA\nPipeline: $CI_PIPELINE_ID" \
+        -d parse_mode=Markdown
